sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wangrongji020303
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tAzais54YTDukVCiWTV
    access-key-secret: ro5rjzYDlnTSfttZXtriLC9W1GcH2I
    bucket-name: java-learn-t
  redis:
    port: 6379
    host: localhost
    database: 10
  wechat:
    appid: wxd577d1941379b3be
    secret: 0e8d79522d51072da6cd925ad5fd9581
